spring.datasource.url=jdbc:postgresql://localhost:5432/smartdoor
spring.datasource.username=smartdoor
spring.datasource.password=smartdoor
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true